### PR TITLE
spelling fix for gender equality goal

### PR DESCRIPTION
**Pull request by dcm31**

### CODE REVIEW

**Comment by dcm31** [comment]
I'm pretty new to github so forgive me if I'm not following any best practices here. -Charlie

**Comment by pythagoraswitch** [comment]
Thank you so much for contributing! Your code passed the checks and everything, and we are merging the pull request. Keep it coming, please!

**Comment by pythagoraswitch** [comment]
FYI - this is now in master branch. As soon as we make the [next release](https://github.com/SDG-data/SDGs/releases), you will see the change you made on our website (when we update [this line](https://github.com/SDG-data/web/blob/gh-pages/assets/list.js#L2)).

:shipit:

**Comment by brunosan** [comment]
:+1:

**Pull request merged**
